# Generated by Django 3.2.20 on 2023-07-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nivaaranapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='models/uploads/')),
            ],
        ),
    ]
